### PR TITLE
Orion k8s setup

### PR DESCRIPTION
**Pull request by marlowl**
I was working on making a besu privacy enabled setup for kubernetes myself, but then I found your pull request and saw that you were already working on this. I tested it on minikube en GKE and still get some small errors. I did make some small adjustments to it and managed to get it working on both minikube and GKE

Things I changed:
 - 4 validator nodes with 4 orion nodes setup
 - Added easy deploy scripts `./deploy.sh` for deployment `./remove.sh` to delete the deployment
 - Added `PRIV` and `EEA` to `--rpc-http-api` to enable private transactions and added `\` to the end of the line as privacy was not enabled for the nodes
 - `http://${ORION1_SERVICE_HOST}:8888` did gave my a besu `uri not valid` error, I hardcoded the url in the configmap and then it works
- Made the nodes gasfree

This setup is running stable for me now, maybe it can also be useful for other people. I am open for feedback/things to change!

### CODE REVIEW

**Comment by marlowl** [comment]
In your branch your calling `http://${ORION1_SERVICE_HOST}:8888` as privacy url, but `ORION1_SERVICE_HOST` is not included as a variable or coming from a configmap or something. That's causing the issue. I hard-coded the full url in the configmap to fix it. 

My last commit is just a clean-up commit that removes nodes without orion attached to it, so it is basically down to 4 besu nodes with privacy enabled and 4 orion instances!

Current setup of my branch survived the weekend without any problems in GKE. I'm also able to create privacy groups and deploy contracts to it. As far as I am concerned this is a mergeable setup right now!

**Comment by marlowl** [comment]
In your branch your calling `http://${ORION1_SERVICE_HOST}:8888` as privacy url, but `ORION1_SERVICE_HOST` is not included as a variable or coming from a configmap or something. That's causing the issue. I hard-coded the full url in the configmap to fix it. 

The last two commits are clean up commits. Current setup of my branch survived the weekend without any problems in GKE. I'm also able to create privacy groups and deploy contracts to it. As far as I am concerned this is a merge-able config/setup right now! Feel free to check/test for yourself!

**Comment by joshuafernandes** [comment]
> I tried to reproduce the URL issue, but I couldn't. Could also have been a config mistake from my side! I don't quite understand why `ORION1_SERVICE_HOST` should work because in your branch it its never mentioned, is this a kubernetes config or something?
> 
> The last two commits are clean up commits. Current setup of my branch survived the weekend without any problems in GKE. I'm also able to create privacy groups and deploy contracts to it. As far as I am concerned this is a merge-able config/setup right now! Feel free to check/test for yourself!

I think I got it, I might have had a typo there in the kubectl setup - should read 'BESU_ORION1_SERVICE_HOST`. That makes more sense and also what I've done in the Helm charts, my apologies for that :(

**Comment by joshuafernandes** [comment]
Apologies for not getting back to you sooner, I'll incorporate your changes to the Helm chart as well and then merge your branch in so both methods are consistent

**Comment by joshuafernandes** [comment]
> Apologies for not getting back to you sooner, I'll incorporate your changes to the Helm chart as well and then merge your branch in so both methods are consistent

**Comment by marlowl** [comment]
Thanks for the review! 

Separate validators and privacy nodes makes sense to me. As far as the typo go's, that happens to all of us I guess!

I did bring back the 2 nodes & node(1-4)privacy deployments and services. As far as I can see this is the same setup as the Helm chart updates you did. If people want to spawn less nodes they can easily throw away the yaml files away and `./deploy.sh` & `./remove.sh` can take care of that. If there is antyhing I missed, let me know!

**Comment by joshuafernandes** [comment]
> Thanks for the review!
> 
> Separate validators and privacy nodes makes sense to me. As far as the typo go's, that happens to all of us I guess!
> 
> I did bring back the 2 nodes & node(1-4)privacy deployments and services. As far as I can see this is the same setup as the Helm chart updates you did. If people want to spawn less nodes they can easily throw away the yaml files away and `./deploy.sh` & `./remove.sh` can take care of that. If there is anything I missed, let me know!

Anytime. Really nice to see people from the community contributing to this too :) Appreciate it!
Thats it, this is for reference implementations that people can tweak to suit their needs. I'm merging now :)

**Pull request merged**
